#! /usr/bin/env python
# encoding: utf-8

PROJECT_NAME = 'videocfg'

def options(opt):
	return

def configure(conf):
	return

def build(bld):
	bld.stlib(
		source = ['videocfg.cpp'],
		target = PROJECT_NAME,
		name = PROJECT_NAME,
		features = 'c cxx',
		includes = ['.', '../public', '../public/tier0', '../public/tier1', '../public/videocfg'],
		use = ['tier0', 'tier1', 'vstdlib'],
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx = bld.get_taskgen_count()
	)
