#! /usr/bin/env python
# encoding: utf-8

def options(opt):
	return

def configure(conf):
	return

def build(bld):
	sources = [
		'gcclient.cpp',
		'gcconstants.cpp',
		'gclogger.cpp',
		'gcmsg.cpp',
		'job.cpp',
		'jobmgr.cpp',
		'jobtime.cpp',
		'messagelist.cpp',
		'msgprotobuf.cpp',
		'netpacket.cpp',
		'netpacketpool.cpp',
		'protobufsharedobject.cpp',
		'sharedobject.cpp',
		'sharedobjectcache.cpp',
		'gcclient_sharedobjectcache.cpp',
		'steamextra/misc.cpp',
		'steamextra/rtime.cpp',
		'steamextra/steamid.cpp',
		'steamextra/tier1/hashglobals.cpp',
		'steamextra/tier1/tsmempool.cpp',
		'steamextra/tier1/tsmultimempool.cpp',
		'workthreadpool.cpp',
		'webapi_response.cpp',
		'generated_proto/steammessages.pb.cc',
		'generated_proto/gcsdk_gcmessages.pb.cc',
		'generated_proto/gcsystemmsgs.pb.cc',
		'../thirdparty/JSON_parser/JSON_parser.c',
	]
	bld.stlib(
		source=sources,
		target='gcsdk',
		name='gcsdk',
		features='c cxx',
		includes=[
			'.',
			'generated_proto',
			'steamextra',
			'..',
			'../common',
			'../public',
			'../public/gcsdk',
			'../public/tier0',
			'../public/tier1',
			'../thirdparty/JSON_parser',
			'../thirdparty/protobuf-2.5.0/src',
		],
		use=['tier0', 'tier1', 'protobuf'],
		subsystem=bld.env.MSVC_SUBSYSTEM,
		idx=bld.get_taskgen_count()
	)
