#! /usr/bin/env python
# encoding: utf-8

from waflib import Utils
import os

top = '.'
PROJECT_NAME = 'mathlib'

def options(opt):
	# stub
	return

def configure(conf):
	conf.define('MATHLIB_LIB',1)

def build(bld):
	source = [
		'capsule.cpp',
		'camera.cpp',
		'cholesky.cpp',
		'color_conversion.cpp',
		'expressioncalculator.cpp',
		'halton.cpp',
		'lightdesc.cpp',
		'mathlib_base.cpp',
		'powsse.cpp',
		'sparse_convolution_noise.cpp',
		'sphere.cpp',
		'sseconst.cpp',
		'sse.cpp',	#				[$WINDOWS||$POSIX]
		'ssenoise.cpp',				
		'anorms.cpp',
		'bumpvects.cpp',
		'IceKey.cpp',
		'imagequant.cpp',
		'polyhedron.cpp',
		'quantize.cpp',
		'randsse.cpp',
		'spherical.cpp',
		'simdvectormatrix.cpp',
		'vector.cpp',
		'vmatrix.cpp',
		'almostequal.cpp'
		,'volumeculler.cpp'
		,'disjoint_set_forest.cpp'
		,'dynamictree.cpp'
		,'eigen.cpp'
		,'femodel.cpp'
		,'femodelbuilder.cpp'
		,'feagglomerator.cpp'
		,'svd.cpp'
		,'transform.cpp'
		,'femodeldesc.cpp'
		,'softbody.cpp'
		,'softbodyenvironment.cpp'
	]
	if bld.env.DEST_CPU in ['x86', 'i386', 'i686']:
		source += ['3dnow.cpp']

	includes = [
		'.',
		'../common',
		'../public',
		'../public/tier0',
		'../public/tier1',
		'../public/mathlib'
	]	

	defines = []

	libs = []

	bld.stlib(
		source   = source,
		target   = PROJECT_NAME,
		name     = PROJECT_NAME,
		features = 'c cxx',
		includes = includes,
		defines  = defines,
		use      = libs,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx      = bld.get_taskgen_count()
	)

