#! /usr/bin/env python
# encoding: utf-8

def options(opt):
	return

def configure(conf):
	return

def build(bld):
	bld.stlib(
		source=[
			'bone_setup.cpp',
			'bone_ik.cpp',
			'bone_utils.cpp',
			'bone_decode.cpp',
			'bone_constraints.cpp',
		],
		target='bonesetup',
		name='bonesetup',
		features='c cxx',
		includes=['.', '../public', '../public/tier0', '../public/tier1'],
		use=['tier0', 'tier1', 'mathlib'],
		subsystem=bld.env.MSVC_SUBSYSTEM,
		idx=bld.get_taskgen_count()
	)
