#! /usr/bin/env python
# encoding: utf-8

from waflib import Utils
import os
import vpc_parser

top = '.'
PROJECT_NAME = 'server'

games = {
	'hl2': ['server_base.vpc', 'server_hl2.vpc'],
	'episodic':['server_base.vpc', 'server_episodic.vpc'],
	'hl2mp': ['server_base.vpc', 'server_hl2mp.vpc'],
	'portal': ['server_base.vpc', 'server_portal.vpc'],
	'hl1': ['server_base.vpc', 'server_hl1.vpc'],
	'hl1mp': ['server_base.vpc', 'server_hl1mp.vpc'],
	'cstrike': ['server_base.vpc', 'server_cstrike.vpc', 'nav_mesh.vpc'],
	'csgo': [
		'server_base.vpc',
		'server_econ_base.vpc',
		'server_cstrike15_inc.vpc',
		'nav_mesh.vpc'
	],
	'dod': ['server_base.vpc', 'server_dod.vpc'],
	'tf': [
		'server_base.vpc',
		'server_econ_base.vpc',
		'tf/tf_gcmessages_include.vpc',
		'nav_mesh.vpc',
		'server_tf.vpc'
	]
}

def options(opt):
	return

def configure(conf):
	game = conf.options.GAMES
	conf.env.GAMES = game

	conf.env.append_unique('DEFINES', ['DISABLE_STEAM=1'])

	if game not in games.keys():
		conf.fatal("Couldn't find game: ", game)

def build(bld):
	game = vpc_parser.parse_vpcs( bld.env, games[bld.env.GAMES], '../..' )

	includes = [
		'.',
		'../shared',
		'../../utils/common',
		'../shared/econ',
		'NextBot',
		'../../common',
		'../../public/tier0',
		'../../public/tier1',
		'../../public'
	]

	defines = []

	libs = ['tier0','particles','dmxloader','tier1','tier2','tier3','mathlib','vstdlib','interfaces','bonesetup','protobuf','gcsdk','responserules_runtime','vgui_controls','choreoobjects','steam_api']
	if bld.env.DEST_OS == 'win32':
		libs += ['USER32']

	install_path = bld.env.PREFIX
	if bld.env.DEST_OS != 'android':
		install_path += '/'+bld.env.GAMES+'/bin'

	source = game["sources"] + [
		'../../common/steamid.cpp',
		'../../public/tier0/memoverride.cpp'
	]
	if bld.env.GAMES == 'csgo':
		source += [
			'generated_proto/base_gcmessages.pb.cc',
			'generated_proto/cstrike15_gcmessages.pb.cc',
			'generated_proto/cstrike15_usermessages.pb.cc',
			'generated_proto/engine_gcmessages.pb.cc',
			'generated_proto/netmessages.pb.cc',
			'generated_proto/network_connection.pb.cc',
			'generated_proto/steammessages.pb.cc',
		]
	includes += game["includes"]
	if bld.env.GAMES == 'csgo':
		includes += [
			'cstrike15',
			'cstrike15/bot',
			'cstrike15/bot/states',
			'cstrike15/hostage',
			'cstrike15/control',
			'generated_proto',
			'../../thirdparty/protobuf-2.5.0/src'
		]
	defines = game["defines"]
	if bld.env.GAMES == 'csgo':
		defines += ['CSGO=1', 'CSTRIKE15=1']

	defines.remove('PROTECTED_THINGS_ENABLE')

	bld.shlib(
		source   = source,
		target   = PROJECT_NAME,
		name     = PROJECT_NAME,
		features = 'c cxx',
		includes = includes,
		defines  = defines,
		install_path = install_path,
		use      = libs,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx      = bld.get_taskgen_count()
	)

