#!/usr/bin/env python3
from __future__ import annotations

import pathlib
import sys
import tempfile
import unittest
from contextlib import redirect_stderr
from io import StringIO


SCRIPT_DIR = pathlib.Path(__file__).resolve().parent
ROOT = SCRIPT_DIR.parent
sys.path.insert(0, str(SCRIPT_DIR))

import vcs_v6


TRACKED_VCS = ROOT / "materialsystem" / "stdshaders" / "shaders" / "fxc"
REFERENCE_VCS = (
    "customclothing_ps20b.vcs",
    "customclothing_vs20.vcs",
    "weapondecal_ps20b.vcs",
    "weapondecal_vs20.vcs",
)


class VcsV6Test(unittest.TestCase):
    def test_legacy_malformed_skip_falls_back_to_false_or_can_be_strict(self) -> None:
        malformed = (
            "($GENERATEMASKS == 0 && GENERATEMASKS1) || "
            "SPRITECARDVERTEXFOG || CROSSHAIR_MODE || LIGHTING_PREVIEW"
        )
        worklist_text = f"""**** generated by fxc_prep.pl ****
#BEGIN legacy_skip
legacy_ps2x.fxc
#DEFINES-D:
GENERATEMASKS=0..1
#DEFINES-S:
#SKIP:
{malformed}
#COMMAND:
fxc.exe /DTOTALSHADERCOMBOS=2 /DCENTROIDMASK=0 /DNUMDYNAMICCOMBOS=2 /DFLAGS=0x0
/Dmain=main /Emain /Tps_2_b /DSHADER_MODEL_PS_2_B=1 /nologo /Foshader.o legacy_ps2x.fxc>output.txt 2>&1
#END
**** end ****
"""
        with tempfile.TemporaryDirectory() as temporary:
            worklist = pathlib.Path(temporary) / "filelist.txt"
            worklist.write_text(worklist_text, encoding="ascii")
            warnings = StringIO()
            with redirect_stderr(warnings):
                section = vcs_v6.parse_worklist(worklist)[0]
            self.assertIsNotNone(section.skip_parse_error)
            self.assertIn("malformed SKIP expression", warnings.getvalue())
            expression, error = vcs_v6._parse_skip_expression(
                section.skip_expression,
                {define.name for define in section.defines},
                section_name=section.name,
            )
            self.assertIsNotNone(error)
            self.assertEqual(0, vcs_v6._evaluate_expression(expression, {"GENERATEMASKS": 0}))
            with self.assertRaises(vcs_v6.VcsError):
                vcs_v6.parse_worklist(worklist, strict_skips=True)

    def test_parse_and_semantically_repack_all_tracked_vcs(self) -> None:
        paths = [TRACKED_VCS / name for name in REFERENCE_VCS]
        self.assertTrue(all(path.is_file() for path in paths))
        for path in paths:
            with self.subTest(path=path.name):
                original = vcs_v6.parse_vcs(path)
                repacked_bytes = vcs_v6.pack_vcs_v6(
                    total_combos=original.header.total_combos,
                    dynamic_combos=original.header.dynamic_combos,
                    combos=original.combos,
                    flags=original.header.flags,
                    centroid_mask=original.header.centroid_mask,
                    source_crc32=original.header.source_crc32,
                )
                repacked = vcs_v6.parse_vcs(repacked_bytes)
                self.assertEqual(original.header.total_combos, repacked.header.total_combos)
                self.assertEqual(original.header.dynamic_combos, repacked.header.dynamic_combos)
                self.assertEqual(original.header.flags, repacked.header.flags)
                self.assertEqual(original.header.centroid_mask, repacked.header.centroid_mask)
                self.assertEqual(original.header.source_crc32, repacked.header.source_crc32)
                self.assertEqual(original.combos, repacked.combos)

    def test_generated_header_dictionary_aliases_and_offsets(self) -> None:
        packed = vcs_v6.pack_vcs_v6(
            total_combos=6,
            dynamic_combos=2,
            combos={
                0: {0: b"A" * 1024, 1: b"B" * 1024},
                1: {0: b"A" * 1024, 1: b"B" * 1024},
                2: {0: b"C" * 1024, 1: b"D" * 1024},
            },
            flags=0x1234,
            centroid_mask=0x55,
            source_crc32=0x89ABCDEF,
            compression="lzma",
        )

        header = vcs_v6.HEADER.unpack_from(packed)
        self.assertEqual((6, 6, 2, 0x1234, 0x55, 3, 0x89ABCDEF), header)
        records = [
            vcs_v6.STATIC_RECORD.unpack_from(packed, vcs_v6.HEADER.size + index * 8)
            for index in range(header[5])
        ]
        self.assertEqual([0, 2, 0xFFFFFFFF], [record[0] for record in records])
        self.assertEqual(len(packed), records[-1][1])

        alias_count_offset = vcs_v6.HEADER.size + header[5] * vcs_v6.STATIC_RECORD.size
        self.assertEqual(1, vcs_v6.U32.unpack_from(packed, alias_count_offset)[0])
        self.assertEqual(
            (1, 0),
            vcs_v6.U32_PAIR.unpack_from(packed, alias_count_offset + vcs_v6.U32.size),
        )
        metadata_end = alias_count_offset + vcs_v6.U32.size + vcs_v6.U32_PAIR.size
        self.assertEqual(metadata_end, records[0][1])
        for index, (_, start) in enumerate(records[:-1]):
            end = records[index + 1][1]
            flag_size = vcs_v6.U32.unpack_from(packed, start)[0]
            self.assertEqual(1, flag_size >> 30)
            payload_size = flag_size & 0x3FFFFFFF
            self.assertEqual(b"LZMA", packed[start + 4 : start + 8])
            self.assertEqual(0xFFFFFFFF, vcs_v6.U32.unpack_from(packed, end - 4)[0])
            self.assertEqual(end, start + 4 + payload_size + 4)

    def test_known_tracked_container_shapes(self) -> None:
        expected = {
            "customclothing_ps20b.vcs": (7, 1, 6, 0),
            "customclothing_vs20.vcs": (1, 1, 1, 0),
            "weapondecal_ps20b.vcs": (200, 5, 40, 10),
            "weapondecal_vs20.vcs": (20, 20, 1, 0),
        }
        for name, shape in expected.items():
            with self.subTest(name=name):
                parsed = vcs_v6.parse_vcs(TRACKED_VCS / name)
                actual = (
                    parsed.header.total_combos,
                    parsed.header.dynamic_combos,
                    len(parsed.combos),
                    len(parsed.static_aliases),
                )
                self.assertEqual(shape, actual)

    def test_real_fxc_two_combo_worklist(self) -> None:
        fxc = ROOT / "dx9sdk" / "utilities" / "fxc.exe"
        shader_dir = ROOT / "materialsystem" / "stdshaders"
        if not fxc.is_file() or sys.platform != "win32":
            self.skipTest("the repo DX9 fxc.exe is Windows-only")
        worklist_text = """**** generated by fxc_prep.pl ****
#BEGIN bufferclearobeystencil_ps20b
bufferclearobeystencil_ps2x.fxc
#DEFINES-D:
#DEFINES-S:
RELOADZCULL=0..1
#SKIP:
0
#COMMAND:
fxc.exe /DTOTALSHADERCOMBOS=2 /DCENTROIDMASK=0 /DNUMDYNAMICCOMBOS=1 /DFLAGS=0x0
/Dmain=main /Emain /Tps_2_b /DSHADER_MODEL_PS_2_B=1 /nologo /Foshader.o bufferclearobeystencil_ps2x.fxc>output.txt 2>&1
#END
**** end ****
"""
        with tempfile.TemporaryDirectory() as temporary:
            worklist = pathlib.Path(temporary) / "filelist.txt"
            worklist.write_text(worklist_text, encoding="ascii")
            section = vcs_v6.parse_worklist(worklist)[0]
            packed = vcs_v6.compile_section(
                section,
                shader_dir=shader_dir,
                fxc=fxc,
                jobs=2,
                source_crc=False,
            )
        parsed = vcs_v6.parse_vcs(packed)
        self.assertEqual((2, 1), (parsed.header.total_combos, parsed.header.dynamic_combos))
        self.assertEqual({0, 1}, set(parsed.combos))
        self.assertEqual({0}, set(parsed.combos[0]))
        self.assertEqual({0}, set(parsed.combos[1]))
        # First DWORD of D3D9 ps_2_b bytecode is 0xffff0201 little-endian.
        self.assertTrue(parsed.combos[0][0].startswith(b"\x01\x02\xff\xff"))
        self.assertTrue(parsed.combos[1][0].startswith(b"\x01\x02\xff\xff"))

    def test_real_fxc_sparse_static_selection_preserves_full_address_space(self) -> None:
        fxc = ROOT / "dx9sdk" / "utilities" / "fxc.exe"
        shader_dir = ROOT / "materialsystem" / "stdshaders"
        if not fxc.is_file() or sys.platform != "win32":
            self.skipTest("the repo DX9 fxc.exe is Windows-only")
        worklist_text = """**** generated by fxc_prep.pl ****
#BEGIN bufferclearobeystencil_ps20b
bufferclearobeystencil_ps2x.fxc
#DEFINES-D:
#DEFINES-S:
RELOADZCULL=0..1
#SKIP:
0
#COMMAND:
fxc.exe /DTOTALSHADERCOMBOS=2 /DCENTROIDMASK=0 /DNUMDYNAMICCOMBOS=1 /DFLAGS=0x0
/Dmain=main /Emain /Tps_2_b /DSHADER_MODEL_PS_2_B=1 /nologo /Foshader.o bufferclearobeystencil_ps2x.fxc>output.txt 2>&1
#END
**** end ****
"""
        with tempfile.TemporaryDirectory() as temporary:
            worklist = pathlib.Path(temporary) / "filelist.txt"
            worklist.write_text(worklist_text, encoding="ascii")
            section = vcs_v6.parse_worklist(worklist)[0]
            packed = vcs_v6.compile_section(
                section,
                shader_dir=shader_dir,
                fxc=fxc,
                jobs=1,
                source_crc=False,
                static_ids=[1],
            )
        parsed = vcs_v6.parse_vcs(packed)
        self.assertEqual((2, 1), (parsed.header.total_combos, parsed.header.dynamic_combos))
        self.assertEqual({1}, set(parsed.combos))
        self.assertEqual({0}, set(parsed.combos[1]))


if __name__ == "__main__":
    unittest.main(verbosity=2)
